arch: &Arch
  optimizer:
    select: 'AdamW'
    AdamW: &AdamW_args
      name: 'AdamW'
      module: 'torch.optim'
      kwargs:
        lr: 0.0003

  scheduler:
    select: 'ExponentialLR'
    ExponentialLR:
      name: 'ExponentialLR'
      module: 'torch.optim.lr_scheduler'
      kwargs:
        gamma: 0.9995
    ConstantLR:
      name: 'ConstantLR'
      module: 'torch.optim.lr_scheduler'
      kwargs:
        total_iters: 0

  loss:
    select: 'CrossEntropyLoss'
    CrossEntropyLoss:
      name: 'CrossEntropyLoss'
      module: 'torch.nn'
      kwargs: {}

  metric:
    select:
      - 'MulticlassAccuracy'
    use_loss: True
    loss_name: 'valid_loss'
    MulticlassAccuracy:
      name: 'MulticlassAccuracy'
      module: 'torchmetrics.classification'
      kwargs:
        num_classes: 8
        average: 'macro'


data:
  datasets:
    train_hdf5_template:
      name: 'HDF5DataSet'
      module: 'custom.dataset.hdf5_dataset'
      kwargs:
        dataset_path: './data/processed/template/train.h5'
    devel_hdf5_template:
      name: 'HDF5DataSet'
      module: 'custom.dataset.hdf5_dataset'
      kwargs:
        dataset_path: './data/processed/template/devel.h5'
    test_hdf5_template:
      name: 'HDF5DataSet'
      module: 'custom.dataset.hdf5_dataset'
      kwargs:
        dataset_path: './data/processed/template/test.h5'

  dataloaders:
    train_loader:
      kwargs:
        batch_size: 32
        shuffle: True
        pin_memory: True
        num_workers: 0
      dataset: 'train_hdf5_template'
    devel_loader:
      kwargs:
        batch_size: 1
        shuffle: False
        pin_memory: True
        num_workers: 0
      dataset: 'devel_hdf5_template'
    test_loader:
      kwargs:
        batch_size: 1
        shuffle: False
        pin_memory: True
        num_workers: 0
      dataset: 'test_hdf5_template'


runner: &Runner
  step_mod: 'grad' # 'epoch' or 'grad'
  total_steps: 1100
  log_freq: 100
  valid_freq: 1000
  save_freq: 500
  seed: 0
  trainer_kwargs:
    grad_acc_steps: 1
  valider_kwargs: {}


ckpt:
  check_metrics:
    - {name: 'MulticlassAccuracy', mod: 'max'}
    - {name: 'valid_loss', mod: 'min'}
  keep_num: 3


WandB:
  project: &P 'Template_project'
  track_params: True
  init_kwargs:
    config:
      arch: *Arch
      runner: *Runner
  watch_kwargs:
    log: 'all'
    log_freq: 1000

